# Generated by Django 5.2 on 2025-05-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0003_alter_usersettings_color_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='conversation_files/')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message_uuid', models.UUIDField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='aquillm.wsconversation')),
            ],
        ),
    ]
