# Generated by Django 5.2.1 on 2025-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0004_conversationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationfile',
            name='message_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
