# Generated by Django 5.2.1 on 2025-10-23 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0005_alter_conversationfile_message_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='zotero_item_key',
            field=models.CharField(blank=True, db_index=True, help_text='Zotero item key to prevent duplicate syncing', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ZoteroConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Zotero API key from OAuth', max_length=255)),
                ('zotero_user_id', models.CharField(help_text='Zotero user ID', max_length=100)),
                ('last_sync_version', models.IntegerField(default=0, help_text='Last synced version number for incremental sync')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time a sync was performed', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
