# Generated by Django 6.0 on 2025-12-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0006_pdfdocument_zotero_item_key_zoteroconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoteroconnection',
            name='last_sync_version',
        ),
    ]
