# Generated by Django 6.0.1 on 2026-02-11 05:18

import aquillm.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0007_remove_zoteroconnection_last_sync_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsconversation',
            name='system_prompt',
            field=models.TextField(blank=True, default=aquillm.models.get_default_system_prompt),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=10)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_call_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_call_input', models.JSONField(blank=True, null=True)),
                ('usage', models.PositiveIntegerField(default=0)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arguments', models.JSONField(blank=True, null=True)),
                ('for_whom', models.CharField(blank=True, choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, null=True)),
                ('result_dict', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_messages', to='aquillm.wsconversation')),
            ],
            options={
                'ordering': ['conversation', 'sequence_number'],
                'indexes': [models.Index(fields=['rating'], name='aquillm_mes_rating_4a344f_idx')],
            },
        ),
    ]
