# Generated by Django 6.0.1 on 2026-02-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0009_migrate_json_to_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsconversation',
            name='convo',
        ),
    ]
