# Generated by Django 6.0.1 on 2026-02-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0010_remove_wsconversation_convo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
