# Generated by Django 6.0 on 2026-03-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquillm', '0011_message_feedback_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeminiAPIUsage',
        ),
    ]
