FROM astral/uv:python3.12-bookworm-slim

ENV PORT=${PORT}
WORKDIR /app

COPY pyproject.toml .
RUN uv sync
RUN apt update && apt install -y curl nodejs npm
COPY . .


WORKDIR /app/aquillm

# Command to run the application
CMD ["sh", "-c", "/app/deployment/run.sh"]
