FROM astral/uv:0.8.17-python3.12-bookworm

ENV UV_PROJECT_ENVIRONMENT=/usr/local

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --group test
RUN apt update && apt install -y curl

COPY . .

WORKDIR /app/aquillm

CMD pytest -s -v --ds=aquillm.settings --reuse-db | tee ../test-results.txt
