FROM debian:bookworm-slim

# Install certbot once during image build
RUN apt update && \
    apt install -y python3 python3-venv libaugeas0 cron && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m venv /opt/certbot/ && \
    /opt/certbot/bin/pip install --no-cache-dir certbot && \
    ln -sf /opt/certbot/bin/certbot /usr/bin/certbot

# Set the entrypoint script
ENTRYPOINT ["/get_certs.sh"]
