# Generated by Django 6.0.3 on 2026-05-19 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_chat', '0004_rename_aquillm_mes_rating_5a0bd9_idx_aquillm_mes_rating_4a344f_idx_and_more'),
        ('apps_collections', '0001_initial_from_aquillm'),
        ('apps_skills', '0002_collectionskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_body_at_generation', models.TextField()),
                ('proposed_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_suggestions', to='apps_collections.collection')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_suggestions', to='apps_chat.message')),
            ],
            options={
                'db_table': 'aquillm_skilleditsuggestion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection', 'status'], name='aquillm_ski_collect_3cbe3e_idx'), models.Index(fields=['source_message', 'status'], name='aquillm_ski_source__797883_idx')],
            },
        ),
    ]
