# Generated by Django 6.0.3 on 2026-05-21 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Skip the auto-generated apps_chat 0005 RenameIndex — the dev DB is
        # already at the new index name; see the matching comment in apps_chat 0004.
        ('apps_chat', '0004_rename_aquillm_mes_rating_5a0bd9_idx_aquillm_mes_rating_4a344f_idx_and_more'),
        ('apps_collections', '0001_initial_from_aquillm'),
        ('apps_skills', '0003_skilleditsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_dismissals', to='apps_collections.collection')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_dismissals', to='apps_chat.message')),
            ],
            options={
                'db_table': 'aquillm_feedbackdismissal',
                'indexes': [models.Index(fields=['collection', 'source_message'], name='aquillm_fee_collect_b0151a_idx')],
                'constraints': [models.UniqueConstraint(fields=('collection', 'source_message'), name='uniq_feedback_dismissal_per_collection_message')],
            },
        ),
    ]
