"""
Django settings for aquillm project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(key: str, default: bool = False) -> bool:
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def env_csv(key: str) -> list[str]:
    value = os.environ.get(key, "")
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(key: str, default: int) -> int:
    try:
        raw = (os.environ.get(key) or str(default)).strip()
        value = int(raw)
    except Exception:
        return default
    return value if value >= 0 else default


def env_float(key: str, default: float) -> float:
    try:
        raw = (os.environ.get(key) or str(default)).strip()
        value = float(raw)
    except Exception:
        return default
    return value if value >= 0 else default


# RAG retrieval caches (fail-open; disabled unless RAG_CACHE_ENABLED=1)
RAG_CACHE_ENABLED = env_bool("RAG_CACHE_ENABLED", False)
RAG_QUERY_EMBED_TTL_SECONDS = env_int("RAG_QUERY_EMBED_TTL_SECONDS", 300)
RAG_DOC_ACCESS_TTL_SECONDS = env_int("RAG_DOC_ACCESS_TTL_SECONDS", 60)
RAG_IMAGE_DATA_URL_TTL_SECONDS = env_int("RAG_IMAGE_DATA_URL_TTL_SECONDS", 120)
RAG_RERANK_RESULT_TTL_SECONDS = env_int("RAG_RERANK_RESULT_TTL_SECONDS", 45)
RAG_RERANK_CAPABILITY_TTL_SECONDS = env_int("RAG_RERANK_CAPABILITY_TTL_SECONDS", 900)

# Hybrid search candidate fan-out (chunk_search); min limits are floors, 0 = unset
RAG_CANDIDATE_MULTIPLIER = env_float("RAG_CANDIDATE_MULTIPLIER", 3.0)
RAG_VECTOR_MIN_LIMIT = env_int("RAG_VECTOR_MIN_LIMIT", 0)
RAG_TRIGRAM_MIN_LIMIT = env_int("RAG_TRIGRAM_MIN_LIMIT", 0)
RAG_TRIGRAM_SIMILARITY_MIN = env_float("RAG_TRIGRAM_SIMILARITY_MIN", 0.000001)
RAG_QUERY_SHORT_LEN = env_int("RAG_QUERY_SHORT_LEN", 48)
RAG_QUERY_LONG_LEN = env_int("RAG_QUERY_LONG_LEN", 160)
RAG_SHORT_QUERY_CANDIDATE_SCALE = env_float("RAG_SHORT_QUERY_CANDIDATE_SCALE", 0.9)
RAG_LONG_QUERY_CANDIDATE_SCALE = env_float("RAG_LONG_QUERY_CANDIDATE_SCALE", 1.1)

# Cross-provider prompt token efficiency (Claude/Gemini mirror OpenAI-style preflight trim)
TOKEN_EFFICIENCY_ENABLED = env_bool("TOKEN_EFFICIENCY_ENABLED", False)
PROMPT_BUDGET_CONTEXT_LIMIT = env_int("PROMPT_BUDGET_CONTEXT_LIMIT", 0)
PROMPT_BUDGET_MAX_TOKENS_CAP = env_int("PROMPT_BUDGET_MAX_TOKENS_CAP", 8192)
PROMPT_BUDGET_SLACK_TOKENS = env_int("PROMPT_BUDGET_SLACK_TOKENS", 384)
PROMPT_COMPRESS_MIN_CHARS = env_int("PROMPT_COMPRESS_MIN_CHARS", 4000)
PROMPT_COMPRESS_TARGET_TOKENS = env_int("PROMPT_COMPRESS_TARGET_TOKENS", 2048)

# Salience-aware context packing (preflight); default off, fail-open
CONTEXT_PACKER_ENABLED = env_bool("CONTEXT_PACKER_ENABLED", False)
CONTEXT_BUDGET_HISTORY_TOKENS = env_int("CONTEXT_BUDGET_HISTORY_TOKENS", 12000)
CONTEXT_BUDGET_TOOL_EVIDENCE_TOKENS = env_int("CONTEXT_BUDGET_TOOL_EVIDENCE_TOKENS", 1400)
CONTEXT_BUDGET_RETRIEVAL_TOKENS = env_int("CONTEXT_BUDGET_RETRIEVAL_TOKENS", 3500)
CONTEXT_PIN_LAST_TURNS = env_int("CONTEXT_PIN_LAST_TURNS", 2)
CONTEXT_MAX_SNIPPETS_PER_DOC = env_int("CONTEXT_MAX_SNIPPETS_PER_DOC", 3)

# Optional LM-Lingua2 (llmlingua) extractive compression; default off, fail-open
LM_LINGUA2_ENABLED = env_bool("LM_LINGUA2_ENABLED", False)
LM_LINGUA2_MODEL = os.environ.get(
    "LM_LINGUA2_MODEL",
    "microsoft/llmlingua-2-xlm-roberta-large-meetingbank",
).strip()
# Empty: adapter picks cuda if torch sees a GPU, else cpu (typical in Docker web).
LM_LINGUA2_DEVICE_MAP = (os.environ.get("LM_LINGUA2_DEVICE_MAP") or "").strip()

# Django cache: Redis when DJANGO_CACHE_REDIS_URL is set; otherwise LocMem (tests/local deterministic)
DJANGO_CACHE_REDIS_URL = (os.environ.get("DJANGO_CACHE_REDIS_URL") or "").strip()
if DJANGO_CACHE_REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": DJANGO_CACHE_REDIS_URL,
            "OPTIONS": {},
            "KEY_PREFIX": os.environ.get("DJANGO_CACHE_KEY_PREFIX", "aquillm"),
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "aquillm-default",
        }
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

SECRET_KEY = ""
if DEBUG:
    SECRET_KEY = "django-insecure-_fj8e0)w#wu48c673prc3$%+h36!df0#)0upbl6t%x#_w3zk60"
else:
    SECRET_KEY = os.environ['SECRET_KEY']

# Application definition

INSTALLED_APPS = [
    "daphne",
    "chat",
    "ingest",
    "django.contrib.sites",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "aquillm",
    # New domain-driven apps
    "apps.collections",
    "apps.documents",
    "apps.chat",
    "apps.ingestion",
    "apps.memory",
    "apps.platform_admin",
    "apps.core",
    "apps.integrations.zotero",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    "django_extensions",
    'django.contrib.postgres',
]

if DEBUG:
    INSTALLED_APPS = list(INSTALLED_APPS) + ["debug_toolbar"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

if DEBUG:
    MIDDLEWARE = list(MIDDLEWARE) + ["debug_toolbar.middleware.DebugToolbarMiddleware"]

ROOT_URLCONF = "aquillm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates', BASE_DIR / 'templates' / 'allauth'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "aquillm.context_processors.nav_links",
                'aquillm.context_processors.user_conversations',
                "aquillm.context_processors.api_urls",
                "aquillm.context_processors.page_urls",
                "aquillm.context_processors.theme_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "aquillm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

POSTGRES_USER = os.environ.get("POSTGRES_USER", "aquillm")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "db")
POSTGRES_NAME = os.environ.get("POSTGRES_NAME", "aquillm")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "aquillm")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_NAME,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": "5432",
        "TEST": {
            'NAME': 'test'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "prod_static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# authentication stuff

SOCIALACCOUNT_LOGIN_ON_GET=True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    ]
if not DEBUG:
    AUTHENTICATION_BACKENDS += [
        'allauth.account.auth_backends.AuthenticationBackend',
    ]


    ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
    ACCOUNT_ADAPTER = 'aquillm.adapters.NoDefaultAccounts'
    SOCIALACCOUNT_ADAPTER = 'aquillm.adapters.RestrictDomains'
    SOCIALACCOUNT_PROVIDERS = {
        'google': {
            'APP': {
                'client_id': os.environ["GOOGLE_OAUTH2_CLIENT_ID"],
                'secret': os.environ["GOOGLE_OAUTH2_CLIENT_SECRET"],
                'key': ''
            },
            'SCOPE': [
                'profile',
                'email',
            ],
            'AUTH_PARAMS': {
                'access_type': 'offline',
            },
            'OAUTH_PKCE_ENABLED': True,
            'FETCH_USERINFO' : True
        }
    }

SITE_ID = 1

INTERNAL_IPS = [
    "127.0.0.1",
]

X_FRAME_OPTIONS = "SAMEORIGIN"
USE_TZ=True
DATA_UPLOAD_MAX_MEMORY_SIZE=  268435456
ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + env_csv("DJANGO_ALLOWED_HOSTS")
if host_name := os.environ.get("HOST_NAME"):
    ALLOWED_HOSTS.append(host_name)
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
ASGI_APPLICATION = "aquillm.asgi.application"


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "endpoint_url": "http://" + os.environ.get("STORAGE_HOST", "storage:9000"),
            "access_key": os.environ.get("STORAGE_ACCESS_KEY", "dev"),
            "secret_key": os.environ.get("STORAGE_SECRET_KEY", "rickbailey"),

            "bucket_name": "aquillm",
            "file_overwrite": False,
        }
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}

CSRF_TRUSTED_ORIGINS = env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")
if host_name:
    CSRF_TRUSTED_ORIGINS.append("https://" + host_name)
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [('redis', 6379)],
        },
    }
}

CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = "redis://redis:6379"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Zotero Integration Settings
# OAuth credentials should be set in environment variables:
# - ZOTERO_CLIENT_KEY: Your Zotero OAuth client key
# - ZOTERO_CLIENT_SECRET: Your Zotero OAuth client secret
# Register your app at https://www.zotero.org/oauth/apps

from aquillm.settings_logging import LOGGING, LOGS_DIR

os.makedirs(LOGS_DIR, exist_ok=True)