# Generated by Django 6.0.3 on 2026-05-19 03:32

import apps.chat.models.conversation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_chat', '0003_wsconversation_selected_collection_ids'),
    ]

    operations = [
        # RenameIndex was auto-generated when adding the SkillEditSuggestion
        # FK to Message, but the dev DB is already at the new index name
        # (Django sometimes regenerates the auto-hashed suffix when the
        # related-name space changes). Skipping the rename here keeps the
        # migration applyable on databases that are already at the target
        # name; the metadata-only AlterField below is still recorded.
        migrations.AlterField(
            model_name='wsconversation',
            name='system_prompt',
            field=models.TextField(blank=True, default=apps.chat.models.conversation.get_default_system_prompt),
        ),
    ]
