# Generated by Django 6.0.3 on 2026-06-16 00:58

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_chat', '0004_message_app_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_number', models.PositiveIntegerField()),
                ('start_sequence', models.PositiveIntegerField()),
                ('end_sequence', models.PositiveIntegerField()),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aquillm_conversationchunk',
                'ordering': ['conversation', 'chunk_number'],
            },
        ),
        migrations.AddField(
            model_name='wsconversation',
            name='index_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wsconversation',
            name='indexed_transcript_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='conversationchunk',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='apps_chat.wsconversation'),
        ),
        migrations.AddIndex(
            model_name='conversationchunk',
            index=models.Index(fields=['conversation'], name='convchunk_conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='convchunk_embedding_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='conversationchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='convchunk_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='conversationchunk',
            constraint=models.UniqueConstraint(fields=('conversation', 'chunk_number'), name='unique_chunk_per_conversation'),
        ),
    ]
