"""
FeedbackQL Parser
=================

This module takes a raw query string typed by a user (or generated by an LLM)
and turns it into a structured Python object the executor can act on.

WHY THIS EXISTS
---------------
We could let admins write raw SQL, but that would be dangerous — SQL can touch
any table in the database. Instead we built a small purpose-built query language
(FeedbackQL) that only understands feedback-related fields. The parser is the
first line of defence: it rejects anything that references a field we haven't
explicitly whitelisted, before any database query runs.

HOW IT WORKS (in plain English)
--------------------------------
Step 1 — Tokenize:
    Split the raw string into a list of "tokens" — the smallest meaningful
    pieces. For example:
        "where rating < 3"  →  [('IDENT','where'), ('IDENT','rating'),
                                 ('OP','<'), ('NUMBER','3')]

Step 2 — Split on pipes:
    FeedbackQL uses "|" to chain clauses (like a Unix pipeline). We split the
    query into stages first, then parse each stage separately.
        "messages | where rating < 3 | limit 10"
        →  ["messages", "where rating < 3", "limit 10"]

Step 3 — Build the AST:
    AST stands for Abstract Syntax Tree. It's just a tree of Python dataclass
    objects that represent the *meaning* of the query in a form the executor
    can work with. For example, "where rating < 3" becomes:
        WhereClause(parts=[Condition(field='rating', op='<', value=3)])

QUERY SYNTAX
------------
    messages
    | where user_id == 5 and rating < 3
    | select user_id, rating, feedback_text, model, created_at
    | order by created_at desc
    | limit 50

    messages
    | where model startswith "gemma"
    | summarize avg_rating = avg(rating), count = count() by model
    | order by avg_rating asc
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from .exceptions import FeedbackQLFieldError, FeedbackQLSyntaxError

# ---------------------------------------------------------------------------
# Allowed fields — the whitelist
# ---------------------------------------------------------------------------
# These are the ONLY field names a query is allowed to reference. Anything
# else raises FeedbackQLFieldError before the executor ever sees it.
# They correspond to columns on the Message table plus a couple of joined
# fields from WSConversation and User (user_id, conversation_id).

ALLOWED_FIELDS = frozenset({
    'rating',               # 1–5 star rating left by the user
    'feedback_text',        # free-text comment alongside the rating
    'feedback_submitted_at',# when the rating was submitted
    'model',                # which AI model produced the message (e.g. 'claude-3-sonnet')
    'role',                 # 'user', 'assistant', or 'tool'
    'content',              # the actual message text
    'sequence_number',      # position of this message in its conversation
    'created_at',           # when the message was stored
    'message_uuid',         # unique ID for the message
    'tool_call_name',       # if this was a tool-use message, which tool was called
    'user_id',              # ID of the user who owns the conversation
    'conversation_id',      # ID of the conversation this message belongs to
})

# Aggregation functions that are valid inside a summarize clause
AGGREGATION_FUNCTIONS = frozenset({'avg', 'count', 'min', 'max', 'sum', 'median'})

# ---------------------------------------------------------------------------
# AST dataclasses
# ---------------------------------------------------------------------------
# Each dataclass below represents one "thing" that can appear in a query.
# The executor receives a Query object and walks these to build ORM calls.

@dataclass
class Condition:
    """
    A single comparison expression, e.g. `rating < 3` or `model startswith "gemma"`.

    field  — the field name being tested (must be in ALLOWED_FIELDS)
    op     — the operator: '==', '!=', '<', '>', '<=', '>=', 'startswith', 'contains', 'in'
    value  — the right-hand side: a number, string, or list (for 'in')
    """
    field: str
    op: str
    value: Any


@dataclass
class WhereClause:
    """
    A `where` clause containing one or more conditions joined by 'and' / 'or'.

    `parts` is a flat list that alternates between Condition objects and
    string connectors. For example:
        "where rating < 3 and user_id == 7"
    becomes:
        WhereClause(parts=[
            Condition('rating', '<', 3),
            'and',
            Condition('user_id', '==', 7),
        ])
    """
    parts: list


@dataclass
class SelectClause:
    """
    A `select` clause that limits which fields appear in the output rows.

    Without a select clause, all allowed fields are returned.
        "select rating, model, user_id"  →  SelectClause(fields=['rating', 'model', 'user_id'])
    """
    fields: list[str]


@dataclass
class Aggregation:
    """
    One aggregation expression inside a summarize clause.

    alias     — the output column name chosen by the query author
    func      — the aggregation function: avg, count, min, max, sum, median
    agg_field — the field being aggregated, or None for count()

    Example: `avg_rating = avg(rating)`
        → Aggregation(alias='avg_rating', func='avg', agg_field='rating')

    Example: `n = count()`
        → Aggregation(alias='n', func='count', agg_field=None)
    """
    alias: str
    func: str
    agg_field: str | None


@dataclass
class SummarizeClause:
    """
    A `summarize` clause that groups rows and computes aggregate values.

    aggregations — list of Aggregation objects (what to compute)
    by           — list of fields to group by (may be empty for a global aggregate)

    Example: `summarize avg_r = avg(rating), n = count() by model`
        → SummarizeClause(
              aggregations=[Aggregation('avg_r','avg','rating'), Aggregation('n','count',None)],
              by=['model']
          )
    """
    aggregations: list[Aggregation]
    by: list[str]


@dataclass
class OrderByClause:
    """
    An `order by` clause. Works on both row-level and summarize queries.

    field     — field name OR a summarize alias (e.g. 'avg_r')
    direction — 'asc' or 'desc' (default 'asc')

    Note: we intentionally do NOT validate `field` against ALLOWED_FIELDS here
    because in a summarize query it may be an alias like 'avg_r' that doesn't
    exist in the database. The executor resolves that in context.
    """
    field: str
    direction: str


@dataclass
class LimitClause:
    """A `limit` clause capping the number of rows returned."""
    n: int


@dataclass
class Query:
    """
    The top-level result of parsing — a list of clause objects in pipeline order.

    The executor processes `clauses` left-to-right, applying each in turn.
    The `messages` keyword at the start of every query is not a clause; it
    just tells the parser this is a FeedbackQL query (and gives us a place to
    extend the language later if needed).
    """
    clauses: list

# ---------------------------------------------------------------------------
# Step 1 — Tokenizer
# ---------------------------------------------------------------------------
# A tokenizer (also called a lexer) breaks a raw string into labelled chunks
# called tokens. We use a single compiled regex with named groups so we can
# identify what kind of token each match is.
#
# Token types:
#   NUMBER    — an integer or decimal: 42, 3.14, -1
#   STRING    — a quoted string: "hello" or 'hello'
#   OP        — a comparison operator: == != <= >= < >
#   EQUALS    — a single = (used in "alias = avg(field)")
#   LBRACKET  — [
#   RBRACKET  — ]
#   LPAREN    — (
#   RPAREN    — )
#   COMMA     — ,
#   IDENT     — an identifier: field names, keywords, aliases

_TOKEN_RE = re.compile(
    r'(?P<NUMBER>-?\d+(?:\.\d+)?)'
    r'|(?P<STRING>"[^"]*"|\'[^\']*\')'
    r'|(?P<OP>==|!=|<=|>=|<|>)'
    r'|(?P<EQUALS>=)'
    r'|(?P<LBRACKET>\[)'
    r'|(?P<RBRACKET>\])'
    r'|(?P<LPAREN>\()'
    r'|(?P<RPAREN>\))'
    r'|(?P<COMMA>,)'
    r'|(?P<IDENT>[a-zA-Z_][a-zA-Z0-9_]*)'
    r'|(?P<SKIP>[ \t\r\n]+)'   # whitespace — discarded
    r'|(?P<MISMATCH>.)'         # anything else — error
)


def _tokenize(text: str) -> list[tuple[str, str]]:
    """
    Convert a string into a list of (token_type, token_value) pairs.
    Whitespace is silently dropped. Any unrecognised character raises an error.
    """
    tokens = []
    for m in _TOKEN_RE.finditer(text):
        kind = m.lastgroup
        value = m.group()
        if kind == 'SKIP':
            continue
        if kind == 'MISMATCH':
            raise FeedbackQLSyntaxError(f"Unexpected character: {value!r}")
        tokens.append((kind, value))
    return tokens

# ---------------------------------------------------------------------------
# Step 2 — Pipeline splitter
# ---------------------------------------------------------------------------

def _split_pipeline(text: str) -> list[str]:
    """
    Split a query on '|' characters to get individual pipeline stages.

    We can't just do text.split('|') because a '|' might appear inside a
    quoted string (unlikely but possible). So we walk character by character,
    tracking whether we're inside quotes or brackets.

    Example:
        'messages | where rating < 3 | limit 10'
        → ['messages', 'where rating < 3', 'limit 10']
    """
    stages: list[str] = []
    depth = 0             # bracket nesting depth — don't split inside [ ] or ( )
    in_string: str | None = None  # which quote char opened the current string, or None
    current: list[str] = []

    for char in text:
        if in_string:
            current.append(char)
            if char == in_string:
                in_string = None   # closing quote
        elif char in ('"', "'"):
            in_string = char
            current.append(char)
        elif char in ('[', '('):
            depth += 1
            current.append(char)
        elif char in (']', ')'):
            depth -= 1
            current.append(char)
        elif char == '|' and depth == 0:
            stages.append(''.join(current).strip())
            current = []
        else:
            current.append(char)

    if current:
        stages.append(''.join(current).strip())

    return [s for s in stages if s]  # drop empty strings

# ---------------------------------------------------------------------------
# Token stream helper — makes the parser code read cleanly
# ---------------------------------------------------------------------------

class _TokenStream:
    """
    A simple wrapper around a list of tokens that supports peek / advance /
    expect operations. This is the standard way to write a hand-rolled parser.

    Think of it like a cursor walking through the token list left-to-right.
    """

    def __init__(self, tokens: list[tuple[str, str]]):
        self._tokens = tokens
        self._pos = 0

    def peek(self) -> tuple[str, str] | None:
        """Return the next token without consuming it, or None if at end."""
        if self._pos < len(self._tokens):
            return self._tokens[self._pos]
        return None

    def peek_value(self) -> str | None:
        """Return the lowercase value of the next token, or None."""
        t = self.peek()
        return t[1].lower() if t else None

    def advance(self) -> tuple[str, str]:
        """Consume and return the next token."""
        t = self._tokens[self._pos]
        self._pos += 1
        return t

    def expect(self, kind: str | None = None, value: str | None = None) -> tuple[str, str]:
        """
        Consume the next token, raising an error if it doesn't match
        the expected kind and/or value.
        """
        t = self.peek()
        if t is None:
            raise FeedbackQLSyntaxError("Unexpected end of clause")
        if kind is not None and t[0] != kind:
            raise FeedbackQLSyntaxError(f"Expected {kind}, got {t[1]!r}")
        if value is not None and t[1].lower() != value.lower():
            raise FeedbackQLSyntaxError(f"Expected {value!r}, got {t[1]!r}")
        return self.advance()

    def expect_ident(self, value: str | None = None) -> str:
        """Shorthand for expect('IDENT', value) that returns just the string."""
        return self.expect('IDENT', value)[1]

    def at_end(self) -> bool:
        return self._pos >= len(self._tokens)

# ---------------------------------------------------------------------------
# Step 3 — Value parsers (used by the condition parser)
# ---------------------------------------------------------------------------

def _parse_value(ts: _TokenStream) -> Any:
    """
    Parse a single literal value: a number, a quoted string, or null.
    Returns a Python int, float, str, or None.
    """
    t = ts.peek()
    if t is None:
        raise FeedbackQLSyntaxError("Expected a value")
    if t[0] == 'NUMBER':
        ts.advance()
        return float(t[1]) if '.' in t[1] else int(t[1])
    if t[0] == 'STRING':
        ts.advance()
        return t[1][1:-1]  # strip the surrounding quote characters
    if t[0] == 'IDENT' and t[1].lower() == 'null':
        ts.advance()
        return None
    raise FeedbackQLSyntaxError(f"Expected a string or number value, got {t[1]!r}")


def _parse_value_list(ts: _TokenStream) -> list:
    """
    Parse a comma-separated list of values up to and including the closing ].
    The opening [ must have already been consumed before calling this.

    Example: the '] of `in [1, 2, 3]`
    """
    values = []
    while True:
        t = ts.peek()
        if t is None:
            raise FeedbackQLSyntaxError("Unterminated list — missing ']'")
        if t[0] == 'RBRACKET':
            ts.advance()
            break
        values.append(_parse_value(ts))
        nxt = ts.peek()
        if nxt and nxt[0] == 'COMMA':
            ts.advance()
    return values


def _validate_field(name: str) -> str:
    """
    Check that `name` is in ALLOWED_FIELDS. Returns the lowercased name if
    valid, raises FeedbackQLFieldError if not.

    This is the whitelist enforcement point for field names.
    """
    lower = name.lower()
    if lower not in ALLOWED_FIELDS:
        raise FeedbackQLFieldError(
            f"Unknown field {name!r}. Allowed fields: {', '.join(sorted(ALLOWED_FIELDS))}"
        )
    return lower

# ---------------------------------------------------------------------------
# Step 3 — Clause parsers
# ---------------------------------------------------------------------------
# Each function below parses one kind of clause from a token stream and
# returns the corresponding AST dataclass.

def _parse_condition(ts: _TokenStream) -> Condition:
    """
    Parse a single comparison condition.

    Supported forms:
        field == value       (exact match)
        field != value       (not equal)
        field < value        (less than)
        field > value        (greater than)
        field <= value       (less than or equal)
        field >= value       (greater than or equal)
        field startswith str (prefix match, case-insensitive)
        field contains str   (substring match, case-insensitive)
        field in [v, v, ...]  (membership test)

    Field name validation is deferred to the executor: a `where` after a
    `summarize` may legitimately reference an aggregate alias (e.g. `avg_r`)
    that isn't in ALLOWED_FIELDS but was defined upstream in the pipeline.
    """
    field_name = ts.expect_ident().lower()

    t = ts.peek()
    if t is None:
        raise FeedbackQLSyntaxError(f"Expected an operator after field {field_name!r}")

    if t[0] == 'OP':
        op = ts.advance()[1]
        value = _parse_value(ts)
        return Condition(field=field_name, op=op, value=value)

    if t[0] == 'IDENT':
        kw = t[1].lower()
        if kw == 'startswith':
            ts.advance()
            return Condition(field=field_name, op='startswith', value=_parse_value(ts))
        if kw == 'contains':
            ts.advance()
            return Condition(field=field_name, op='contains', value=_parse_value(ts))
        if kw == 'in':
            ts.advance()
            ts.expect('LBRACKET')
            return Condition(field=field_name, op='in', value=_parse_value_list(ts))

    raise FeedbackQLSyntaxError(
        f"Expected a comparison operator (==, !=, <, >, <=, >=, startswith, contains, in), "
        f"got {t[1]!r}"
    )


def _parse_where(ts: _TokenStream) -> WhereClause:
    """
    Parse: condition ('and' | 'or' condition)*

    Conditions are joined left-to-right. We don't support parenthesised
    grouping — it's not needed for the queries we expect admins to write.
    """
    parts: list = [_parse_condition(ts)]
    while not ts.at_end():
        t = ts.peek()
        if t and t[0] == 'IDENT' and t[1].lower() in ('and', 'or'):
            parts.append(ts.advance()[1].lower())   # 'and' or 'or'
            parts.append(_parse_condition(ts))
        else:
            break
    return WhereClause(parts=parts)


def _parse_select(ts: _TokenStream) -> SelectClause:
    """Parse: field (, field)*"""
    fields = [_validate_field(ts.expect_ident())]
    while not ts.at_end() and ts.peek() and ts.peek()[0] == 'COMMA':
        ts.advance()
        fields.append(_validate_field(ts.expect_ident()))
    return SelectClause(fields=fields)


def _parse_aggregation(ts: _TokenStream) -> Aggregation:
    """
    Parse one aggregation expression: alias = func(field?)

    Examples:
        avg_rating = avg(rating)
        n = count()
        lowest = min(rating)
    """
    alias = ts.expect_ident()          # user-chosen output column name
    ts.expect('EQUALS')                # the = sign
    func_token = ts.expect_ident()     # function name
    func = func_token.lower()
    if func not in AGGREGATION_FUNCTIONS:
        raise FeedbackQLSyntaxError(
            f"Unknown aggregation function {func_token!r}. "
            f"Allowed: {', '.join(sorted(AGGREGATION_FUNCTIONS))}"
        )
    ts.expect('LPAREN')
    # The field inside the parens is optional — count() takes no argument
    agg_field = None
    t = ts.peek()
    if t and t[0] == 'IDENT':
        agg_field = _validate_field(ts.advance()[1])
    ts.expect('RPAREN')
    return Aggregation(alias=alias, func=func, agg_field=agg_field)


def _parse_summarize(ts: _TokenStream) -> SummarizeClause:
    """
    Parse: agg_expr (, agg_expr)* (by field (, field)*)?

    Examples:
        summarize n = count()
        summarize avg_r = avg(rating), n = count() by model
        summarize avg_r = avg(rating) by model, user_id
    """
    aggs = [_parse_aggregation(ts)]
    while ts.peek() and ts.peek()[0] == 'COMMA':
        ts.advance()
        aggs.append(_parse_aggregation(ts))

    by_fields: list[str] = []
    if ts.peek() and ts.peek_value() == 'by':
        ts.advance()
        by_fields.append(_validate_field(ts.expect_ident()))
        while ts.peek() and ts.peek()[0] == 'COMMA':
            ts.advance()
            by_fields.append(_validate_field(ts.expect_ident()))

    return SummarizeClause(aggregations=aggs, by=by_fields)


def _parse_order_by(ts: _TokenStream) -> OrderByClause:
    """
    Parse: by field (asc | desc)?

    The `order` keyword has already been consumed by the caller.
    `field` is NOT validated against ALLOWED_FIELDS here because in a
    summarize query it may be an alias (like 'avg_r') that was defined in
    the summarize clause. The executor validates it in context.
    """
    ts.expect_ident('by')
    field_name = ts.expect_ident().lower()
    direction = 'asc'
    if ts.peek() and ts.peek_value() in ('asc', 'desc'):
        direction = ts.advance()[1].lower()
    return OrderByClause(field=field_name, direction=direction)


def _parse_limit(ts: _TokenStream) -> LimitClause:
    """Parse: number (must be a positive integer)."""
    t = ts.expect('NUMBER')
    n = int(float(t[1]))
    if n <= 0:
        raise FeedbackQLSyntaxError("LIMIT must be a positive integer")
    return LimitClause(n=n)


def _parse_clause(text: str):
    """
    Parse a single pipeline stage (everything between two pipes).
    Looks at the first keyword to determine which kind of clause it is.
    """
    tokens = _tokenize(text)
    if not tokens:
        raise FeedbackQLSyntaxError("Empty clause")
    ts = _TokenStream(tokens)

    kw = ts.peek_value()
    if kw == 'where':
        ts.advance()
        return _parse_where(ts)
    if kw == 'select':
        ts.advance()
        return _parse_select(ts)
    if kw == 'summarize':
        ts.advance()
        return _parse_summarize(ts)
    if kw == 'order':
        ts.advance()
        return _parse_order_by(ts)
    if kw == 'limit':
        ts.advance()
        return _parse_limit(ts)

    raise FeedbackQLSyntaxError(
        f"Unknown clause {text.split()[0]!r}. "
        f"Expected: where, select, summarize, order by, limit"
    )

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def parse(text: str) -> Query:
    """
    Parse a FeedbackQL query string and return a Query AST.

    Raises FeedbackQLSyntaxError if the query is malformed.
    Raises FeedbackQLFieldError if the query references a disallowed field.

    The returned Query is a plain Python object — no database calls happen here.
    Pass it to executor.execute() to actually run it.
    """
    stages = _split_pipeline(text)
    if not stages:
        raise FeedbackQLSyntaxError("Empty query")

    if stages[0].lower() != 'messages':
        raise FeedbackQLSyntaxError(
            f"Query must start with 'messages', got {stages[0]!r}"
        )

    # Parse each pipeline stage into a clause object
    clauses = [_parse_clause(stage) for stage in stages[1:]]
    return Query(clauses=clauses)
