FROM python:3.12-slim

ENV PORT=${PORT}
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt update && apt install -y curl nodejs npm tesseract-ocr \
    libreoffice-writer-nogui libreoffice-calc-nogui libreoffice-impress-nogui
COPY . .


WORKDIR /app/aquillm

# Command to run the application
CMD ["sh", "/app/deploy/scripts/run.sh"]
