FROM astral/uv:0.8.17-python3.12-bookworm

ENV PORT=${PORT}
WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev
RUN apt update && apt install -y curl nodejs npm tesseract-ocr \
    libreoffice-writer-nogui libreoffice-calc-nogui libreoffice-impress-nogui
COPY . .


WORKDIR /app/aquillm

# Command to run the application
CMD ["sh", "/app/deploy/scripts/run.sh"]
