apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":\s*"([a-f0-9]{32})"'
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: View Trace
        - name: TraceID-PG
          matcherRegex: "traceparent='00-([a-f0-9]{32})-[a-f0-9]{16}-[a-f0-9]{2}'"
          url: "$${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: View Trace

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: false
        filterBySpanID: false
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        customQuery: true
        query: '{service_name=~".+"} | json | trace_id=`$${__trace.traceId}`'
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
      nodeGraph:
        enabled: true

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    uid: pyroscope
    url: http://pyroscope:4040

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
