# Generated by Django 5.2.12 on 2026-08-18 10:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_collections", "0001_initial_from_aquillm"),
        ("apps_documents", "0003_document_source_url"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                ("normalized_label", models.CharField(max_length=512)),
                ("entity_type", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "normalized_label"],
                        name="kg_canonical_entity_lookup",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["active", "suppressed", "rejected", "superseded"],
                            )
                        ),
                        name="kg_canonical_entity_status_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionArtifactInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("source_signature", models.CharField(editable=False, max_length=64)),
                (
                    "membership_signature",
                    models.CharField(editable=False, max_length=64),
                ),
                ("build_signature", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="knowledge_graph_inputs",
                        to="apps_collections.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_key", models.CharField(editable=False, max_length=64)),
                ("label", models.TextField()),
                ("normalized_label", models.CharField(max_length=512)),
                (
                    "version_signature",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=128
                    ),
                ),
                ("entity_type", models.CharField(max_length=128)),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("extraction_confidence", models.FloatField()),
                ("resolution_confidence", models.FloatField()),
                ("retrieval_utility", models.FloatField()),
                ("promotion_confidence", models.FloatField(blank=True, null=True)),
                (
                    "filter_reason",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "embedding_model_signature",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=512
                    ),
                ),
                (
                    "embedding_input_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_graph_entities",
                        to="apps_collections.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("collection", "Collection"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="building",
                        max_length=16,
                    ),
                ),
                ("source_hash", models.CharField(max_length=64)),
                ("ontology_version", models.CharField(max_length=128)),
                ("extractor_version", models.CharField(max_length=128)),
                ("resolver_version", models.CharField(max_length=128)),
                ("filter_policy_version", models.CharField(max_length=128)),
                (
                    "embedding_model_signature",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "ontology_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "filter_policy_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "resolution_config_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope_type", "scope_id", "status"],
                        name="kg_art_scope_status_idx",
                    ),
                    models.Index(fields=["source_hash"], name="kg_art_source_hash_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scope_type__in", ("document", "collection"))
                        ),
                        name="kg_artifact_scope_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "scope_id__regex",
                                    "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
                                ),
                                ("scope_type", "document"),
                            ),
                            models.Q(
                                ("scope_id__regex", "^[1-9][0-9]*$"),
                                ("scope_type", "collection"),
                            ),
                            _connector="OR",
                        ),
                        name="kg_artifact_typed_scope_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("embedding_model_signature", ""),
                                ("scope_type", "document"),
                            ),
                            models.Q(
                                ("scope_type", "collection"),
                                models.Q(
                                    ("embedding_model_signature", ""), _negated=True
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="kg_artifact_embedding_signature_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ontology_checksum__regex", "^[0-9a-f]{64}$"),
                            ("filter_policy_checksum__regex", "^[0-9a-f]{64}$"),
                            ("resolution_config_checksum__regex", "^[0-9a-f]{64}$"),
                        ),
                        name="kg_artifact_identity_checksums_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "building",
                                    "active",
                                    "failed",
                                    "stale",
                                    "suppressed",
                                    "rejected",
                                    "superseded",
                                ),
                            )
                        ),
                        name="kg_artifact_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_hash", ""), _negated=True),
                        name="kg_artifact_source_hash_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ontology_version", ""), _negated=True),
                        name="kg_artifact_ontology_ver_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("extractor_version", ""), _negated=True),
                        name="kg_artifact_extractor_ver_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("resolver_version", ""), _negated=True),
                        name="kg_artifact_resolver_ver_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("filter_policy_version", ""), _negated=True
                        ),
                        name="kg_artifact_filter_ver_nonempty",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("scope_type", "scope_id"),
                        name="kg_one_active_artifact_per_scope",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "scope_type",
                            "scope_id",
                            "source_hash",
                            "ontology_version",
                            "extractor_version",
                            "resolver_version",
                            "filter_policy_version",
                            "embedding_model_signature",
                            "ontology_checksum",
                            "filter_policy_checksum",
                            "resolution_config_checksum",
                        ),
                        name="kg_artifact_build_identity",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                (
                    "position_basis",
                    models.CharField(
                        choices=[
                            ("document_global", "Document global"),
                            ("chunk_content", "Chunk content"),
                        ],
                        max_length=24,
                    ),
                ),
                ("raw_text", models.TextField()),
                ("normalized_text", models.CharField(max_length=512)),
                ("entity_type", models.CharField(max_length=128)),
                ("extraction_confidence", models.FloatField()),
                ("content_object_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_entity_mentions",
                        to="apps_documents.textchunk",
                    ),
                ),
                (
                    "content_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mentions",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("cluster_key", models.CharField(editable=False, max_length=64)),
                ("label", models.TextField()),
                ("normalized_label", models.CharField(max_length=512)),
                (
                    "version_signature",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=128
                    ),
                ),
                ("resolution_confidence", models.FloatField(default=1.0)),
                ("entity_type", models.CharField(max_length=128)),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_entities",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("support_count", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="apps_knowledge_graph.collectionentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="apps_knowledge_graph.collectionentity",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_relations",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionEntityDocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("identifier_score", models.FloatField(blank=True, null=True)),
                ("alias_score", models.FloatField(blank=True, null=True)),
                ("embedding_similarity", models.FloatField(blank=True, null=True)),
                ("neighborhood_agreement", models.FloatField(blank=True, null=True)),
                ("method", models.CharField(max_length=64)),
                ("resolver_version", models.CharField(max_length=128)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("candidate", "Candidate"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("candidate_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("decision_checksum", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="apps_knowledge_graph.collectionentity",
                    ),
                ),
                (
                    "manifest_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entity_links",
                        to="apps_knowledge_graph.collectionartifactinput",
                    ),
                ),
                (
                    "document_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_links",
                        to="apps_knowledge_graph.documententity",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_entity_links",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collectionentity",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_entities",
                to="apps_knowledge_graph.graphartifact",
            ),
        ),
        migrations.AddField(
            model_name="collectionartifactinput",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_inputs",
                to="apps_knowledge_graph.graphartifact",
            ),
        ),
        migrations.AddField(
            model_name="collectionartifactinput",
            name="document_artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="collection_build_uses",
                to="apps_knowledge_graph.graphartifact",
            ),
        ),
        migrations.CreateModel(
            name="GraphBuildRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "build_kind",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("collection", "Collection"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("collection", "Collection"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_id", models.CharField(max_length=64)),
                ("source_hash", models.CharField(max_length=64)),
                ("ontology_version", models.CharField(max_length=128)),
                ("extractor_version", models.CharField(max_length=128)),
                ("resolver_version", models.CharField(max_length=128)),
                ("filter_policy_version", models.CharField(max_length=128)),
                (
                    "embedding_model_signature",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "ontology_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "filter_policy_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "resolution_config_checksum",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ontology", "Ontology"),
                            ("extraction", "Extraction"),
                            ("resolution", "Resolution"),
                            ("filtering", "Filtering"),
                            ("persistence", "Persistence"),
                            ("complete", "Complete"),
                        ],
                        default="ontology",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_metadata", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("timings", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="build_runs",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OntologyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("entity", "Entity"),
                            ("relation", "Relation"),
                            ("graph", "Graph"),
                        ],
                        max_length=16,
                    ),
                ),
                ("version", models.CharField(max_length=128)),
                ("checksum", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "status"], name="kg_ontology_kind_status_idx"
                    ),
                    models.Index(fields=["checksum"], name="kg_ontology_checksum_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ("entity", "relation", "graph"))
                        ),
                        name="kg_ontology_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ("draft", "active", "superseded", "rejected"),
                            )
                        ),
                        name="kg_ontology_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version", ""), _negated=True),
                        name="kg_ontology_version_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("checksum", ""), _negated=True),
                        name="kg_ontology_checksum_nonempty",
                    ),
                    models.UniqueConstraint(
                        fields=("kind", "version"),
                        name="kg_ontology_kind_version_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RelationMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("relation_type", models.CharField(max_length=128)),
                ("extraction_confidence", models.FloatField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_mentions",
                        to="apps_knowledge_graph.graphartifact",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_relation_mentions",
                        to="apps_documents.textchunk",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relation_mentions",
                        to="apps_knowledge_graph.entitymention",
                    ),
                ),
                (
                    "tail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relation_mentions",
                        to="apps_knowledge_graph.entitymention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionRelationEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "head_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="head_relation_evidence",
                        to="apps_knowledge_graph.collectionentitydocumentlink",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="apps_knowledge_graph.collectionrelation",
                    ),
                ),
                (
                    "tail_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tail_relation_evidence",
                        to="apps_knowledge_graph.collectionentitydocumentlink",
                    ),
                ),
                (
                    "relation_mention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_evidence_links",
                        to="apps_knowledge_graph.relationmention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalEntityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("method", models.CharField(max_length=64)),
                ("resolver_version", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_links",
                        to="apps_knowledge_graph.canonicalentity",
                    ),
                ),
                (
                    "collection_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_links",
                        to="apps_knowledge_graph.collectionentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "canonical_entity"],
                        name="kg_can_link_canonical_idx",
                    ),
                    models.Index(
                        fields=["status", "collection_entity"],
                        name="kg_can_link_collection_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["active", "suppressed", "rejected", "superseded"],
                            )
                        ),
                        name="kg_canonical_link_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                        name="kg_collection_canonical_score_range",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "collection_entity",
                            "canonical_entity",
                            "resolver_version",
                        ),
                        name="kg_collection_canonical_link_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentEntityMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suppressed", "Suppressed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("root", "Cluster root"),
                            ("stable_identifier", "Stable identifier"),
                            ("defined_acronym", "Defined acronym"),
                            ("ontology_alias", "Ontology alias"),
                            ("normalized_name", "Normalized name"),
                            ("singleton", "Singleton"),
                        ],
                        max_length=64,
                    ),
                ),
                ("resolver_version", models.CharField(max_length=128)),
                (
                    "parent_mention_id",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=128
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mention_links",
                        to="apps_knowledge_graph.documententity",
                    ),
                ),
                (
                    "mention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_entity_link",
                        to="apps_knowledge_graph.entitymention",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "document_entity"],
                        name="kg_doc_mention_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["active", "suppressed", "rejected", "superseded"],
                            )
                        ),
                        name="kg_document_mention_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "method__in",
                                (
                                    "root",
                                    "stable_identifier",
                                    "defined_acronym",
                                    "ontology_alias",
                                    "normalized_name",
                                    "singleton",
                                ),
                            )
                        ),
                        name="kg_document_mention_method_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("resolver_version", ""), _negated=True),
                        name="kg_document_mention_resolver_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("method__in", ("root", "singleton")),
                                ("parent_mention_id", ""),
                            ),
                            models.Q(
                                models.Q(
                                    ("method__in", ("root", "singleton")), _negated=True
                                ),
                                models.Q(("parent_mention_id", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="kg_document_mention_parent_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="entitymention",
            index=models.Index(
                fields=["document_id", "chunk"], name="kg_mention_doc_chunk_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitymention",
            index=models.Index(
                fields=["normalized_text", "entity_type"],
                name="kg_mention_norm_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entitymention",
            index=models.Index(
                fields=["content_object_type", "content_object_id"],
                name="kg_mention_content_obj_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymention",
            constraint=models.CheckConstraint(
                condition=models.Q(("start__gte", 0), ("end__gt", models.F("start"))),
                name="kg_mention_nonempty_span",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__gte", 0), ("extraction_confidence__lte", 1)
                ),
                name="kg_mention_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position_basis__in", ("document_global", "chunk_content"))
                ),
                name="kg_mention_position_basis_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("content_object_id__isnull", True),
                        ("content_object_type__isnull", True),
                        ("position_basis", "document_global"),
                    ),
                    models.Q(
                        ("content_object_id__isnull", False),
                        ("content_object_type__isnull", False),
                        ("position_basis", "chunk_content"),
                    ),
                    _connector="OR",
                ),
                name="kg_mention_basis_provenance",
            ),
        ),
        migrations.AddIndex(
            model_name="documententity",
            index=models.Index(
                fields=["document_id", "entity_type", "normalized_label"],
                name="kg_doc_entity_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "suppressed", "rejected", "superseded"])
                ),
                name="kg_document_entity_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier", ""), _negated=True),
                fields=("artifact", "entity_type", "identifier", "version_signature"),
                name="kg_document_entity_identifier_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.UniqueConstraint(
                fields=("artifact", "cluster_key"),
                name="kg_document_entity_cluster_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier", ""),
                    models.Q(("identifier__regex", "^\\s+$"), _negated=True),
                    _connector="OR",
                ),
                name="kg_document_identifier_not_ws",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.CheckConstraint(
                condition=models.Q(("cluster_key__regex", "^[0-9a-f]{64}$")),
                name="kg_document_cluster_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version_signature", ""),
                    ("version_signature__regex", "^[a-z0-9][a-z0-9.+:/_-]*$"),
                    _connector="OR",
                ),
                name="kg_document_version_signature_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documententity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolution_confidence__gte", 0), ("resolution_confidence__lte", 1)
                ),
                name="kg_document_resolution_conf_range",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionrelation",
            index=models.Index(
                fields=["artifact", "source", "target", "relation_type"],
                name="kg_collection_relation_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "suppressed", "rejected", "superseded"])
                ),
                name="kg_collection_relation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelation",
            constraint=models.UniqueConstraint(
                fields=("artifact", "source", "relation_type", "target"),
                name="kg_collection_relation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("support_count__gte", 0)),
                name="kg_collection_relation_support",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="kg_collection_relation_conf",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="kg_collection_relation_endpoints",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentitydocumentlink",
            index=models.Index(
                fields=["status", "collection_entity"],
                name="kg_doc_link_collection_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentitydocumentlink",
            index=models.Index(
                fields=["status", "document_entity"], name="kg_doc_link_document_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentitydocumentlink",
            index=models.Index(
                fields=["artifact", "outcome", "document_entity"],
                name="kg_doc_link_outcome_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "suppressed", "rejected", "superseded"])
                ),
                name="kg_doc_collection_link_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                name="kg_doc_collection_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier_score__isnull", True),
                    models.Q(
                        ("identifier_score__gte", 0), ("identifier_score__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="kg_doc_link_identifier_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("alias_score__isnull", True),
                    models.Q(("alias_score__gte", 0), ("alias_score__lte", 1)),
                    _connector="OR",
                ),
                name="kg_doc_link_alias_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("embedding_similarity__isnull", True),
                    models.Q(
                        ("embedding_similarity__gte", 0),
                        ("embedding_similarity__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="kg_doc_link_embedding_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("neighborhood_agreement__isnull", True),
                    models.Q(
                        ("neighborhood_agreement__gte", 0),
                        ("neighborhood_agreement__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="kg_doc_link_neighbor_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__in", ("automatic", "candidate", "rejected"))
                ),
                name="kg_doc_collection_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("candidate_rank__isnull", True), ("outcome", "automatic")
                    ),
                    models.Q(
                        ("candidate_rank__isnull", False), ("outcome", "candidate")
                    ),
                    ("outcome", "rejected"),
                    _connector="OR",
                ),
                name="kg_doc_collection_candidate_rank",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "automatic"), ("status", "active")),
                    models.Q(("outcome", "candidate"), ("status", "suppressed")),
                    models.Q(("outcome", "rejected"), ("status", "rejected")),
                    _connector="OR",
                ),
                name="kg_doc_collection_outcome_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision_checksum__regex", "^[0-9a-f]{64}$")),
                name="kg_doc_collection_decision_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.UniqueConstraint(
                fields=(
                    "artifact",
                    "document_entity",
                    "collection_entity",
                    "resolver_version",
                ),
                name="kg_doc_collection_entity_link_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentitydocumentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "automatic")),
                fields=("artifact", "document_entity"),
                name="kg_one_auto_collection_assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentity",
            index=models.Index(
                fields=["artifact", "collection", "entity_type", "normalized_label"],
                name="kg_collection_entity_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "suppressed", "rejected", "superseded"])
                ),
                name="kg_collection_entity_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier", ""), _negated=True),
                fields=("artifact", "entity_type", "identifier", "version_signature"),
                name="kg_collection_entity_identifier_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.UniqueConstraint(
                fields=("artifact", "cluster_key"),
                name="kg_collection_entity_cluster_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identifier", ""),
                    models.Q(("identifier__regex", "^\\s+$"), _negated=True),
                    _connector="OR",
                ),
                name="kg_collection_identifier_not_ws",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("cluster_key__regex", "^[0-9a-f]{64}$")),
                name="kg_collection_cluster_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version_signature", ""),
                    ("version_signature__regex", "^[a-z0-9][a-z0-9.+:/_-]*$"),
                    _connector="OR",
                ),
                name="kg_collection_version_signature_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__gte", 0), ("extraction_confidence__lte", 1)
                ),
                name="kg_collection_extract_conf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolution_confidence__gte", 0), ("resolution_confidence__lte", 1)
                ),
                name="kg_collection_resolve_conf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retrieval_utility__gte", 0), ("retrieval_utility__lte", 1)
                ),
                name="kg_collection_utility_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotion_confidence__isnull", True),
                    models.Q(
                        ("promotion_confidence__gte", 0),
                        ("promotion_confidence__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="kg_collection_promotion_conf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("embedding__isnull", True),
                        ("embedding_input_hash", ""),
                        ("embedding_model_signature", ""),
                    ),
                    models.Q(
                        ("embedding__isnull", False),
                        models.Q(("embedding_model_signature", ""), _negated=True),
                        ("embedding_input_hash__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="kg_collection_embedding_audit_complete",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionartifactinput",
            index=models.Index(
                fields=["artifact", "collection", "document_id"],
                name="kg_collection_input_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionartifactinput",
            constraint=models.UniqueConstraint(
                fields=("artifact", "document_id"),
                name="kg_collection_input_document_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionartifactinput",
            constraint=models.UniqueConstraint(
                fields=("artifact", "document_artifact"),
                name="kg_collection_input_artifact_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionartifactinput",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_signature__regex", "^[0-9a-f]{64}$")),
                name="kg_collection_input_source_sig_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionartifactinput",
            constraint=models.CheckConstraint(
                condition=models.Q(("membership_signature__regex", "^[0-9a-f]{64}$")),
                name="kg_collection_input_membership_sig_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionartifactinput",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_signature__regex", "^[0-9a-f]{64}$")),
                name="kg_collection_input_build_sig_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["artifact", "status"], name="kg_run_art_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["status", "stage"], name="kg_run_status_stage_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_kind__in", ("document", "collection"))),
                name="kg_build_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["document", "collection"])),
                name="kg_build_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "scope_id__regex",
                            "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
                        ),
                        ("scope_type", "document"),
                    ),
                    models.Q(
                        ("scope_id__regex", "^[1-9][0-9]*$"),
                        ("scope_type", "collection"),
                    ),
                    _connector="OR",
                ),
                name="kg_run_typed_scope_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("embedding_model_signature", ""), ("scope_type", "document")
                    ),
                    models.Q(
                        ("scope_type", "collection"),
                        models.Q(("embedding_model_signature", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="kg_run_embedding_signature_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ontology_checksum__regex", "^[0-9a-f]{64}$"),
                    ("filter_policy_checksum__regex", "^[0-9a-f]{64}$"),
                    ("resolution_config_checksum__regex", "^[0-9a-f]{64}$"),
                ),
                name="kg_run_identity_checksums_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "ontology",
                            "extraction",
                            "resolution",
                            "filtering",
                            "persistence",
                            "complete",
                        ),
                    )
                ),
                name="kg_build_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("pending", "running", "succeeded", "failed", "cancelled"),
                    )
                ),
                name="kg_build_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_hash", ""), _negated=True),
                    models.Q(("ontology_version", ""), _negated=True),
                    models.Q(("extractor_version", ""), _negated=True),
                    models.Q(("resolver_version", ""), _negated=True),
                    models.Q(("filter_policy_version", ""), _negated=True),
                ),
                name="kg_build_snapshot_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gte", 1)),
                name="kg_build_run_attempt_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="relationmention",
            index=models.Index(
                fields=["artifact", "document_id", "chunk"],
                name="kg_rel_mention_evidence_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relationmention",
            index=models.Index(
                fields=["artifact", "relation_type"], name="kg_rel_mention_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="relationmention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__gte", 0), ("extraction_confidence__lte", 1)
                ),
                name="kg_relation_mention_conf_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationmention",
            constraint=models.CheckConstraint(
                condition=models.Q(("head", models.F("tail")), _negated=True),
                name="kg_relation_mention_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrelationevidence",
            constraint=models.UniqueConstraint(
                fields=("relation", "relation_mention"),
                name="kg_relation_evidence_unique",
            ),
        ),
    ]
