# Generated by Django 5.2.12 on 2026-08-18 16:26

import hashlib
import json

from django.db import migrations, models

_ARTIFACT_IDENTITY_FIELDS = (
    "scope_type",
    "scope_id",
    "source_hash",
    "ontology_version",
    "extractor_version",
    "resolver_version",
    "filter_policy_version",
    "embedding_model_signature",
    "ontology_checksum",
    "filter_policy_checksum",
    "resolution_config_checksum",
    "assembly_version",
    "assembly_config_checksum",
)


def _digest(payload):
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def populate_build_keys(apps, schema_editor):
    GraphArtifact = apps.get_model("apps_knowledge_graph", "GraphArtifact")
    GraphBuildRun = apps.get_model("apps_knowledge_graph", "GraphBuildRun")
    batch_size = 1_000
    artifact_batch = []
    previous_scope = None
    build_generation = 0
    artifacts = GraphArtifact.objects.order_by("scope_type", "scope_id", "pk")
    for artifact in artifacts.iterator(chunk_size=batch_size):
        scope = (artifact.scope_type, artifact.scope_id)
        if scope != previous_scope:
            previous_scope = scope
            build_generation = 0
        build_generation += 1
        artifact.build_key = _digest(
            {
                "namespace": "legacy-graph-artifact-v1",
                "identity": {
                    field: str(getattr(artifact, field, ""))
                    for field in _ARTIFACT_IDENTITY_FIELDS
                },
            }
        )
        artifact.build_generation = build_generation
        metadata = artifact.metadata if type(artifact.metadata) is dict else {}
        artifact.orchestration_version = int(metadata.get("orchestration_version") == 1)
        artifact_batch.append(artifact)
        if len(artifact_batch) >= batch_size:
            GraphArtifact.objects.bulk_update(
                artifact_batch,
                ["build_key", "build_generation", "orchestration_version"],
                batch_size=batch_size,
            )
            artifact_batch.clear()
    if artifact_batch:
        GraphArtifact.objects.bulk_update(
            artifact_batch,
            ["build_key", "build_generation", "orchestration_version"],
            batch_size=batch_size,
        )

    run_batch = []
    runs = GraphBuildRun.objects.select_related("artifact").order_by("pk")
    for run in runs.iterator(chunk_size=batch_size):
        if run.artifact_id is None:
            run.build_key = _digest(
                {
                    "namespace": "legacy-detached-graph-run-v1",
                    "run_id": run.pk,
                }
            )
            run.build_generation = 1
            run.orchestration_version = 0
        else:
            run.build_key = run.artifact.build_key
            run.build_generation = run.artifact.build_generation
            run.orchestration_version = run.artifact.orchestration_version
        run.build_kind = run.scope_type
        run_batch.append(run)
        if len(run_batch) >= batch_size:
            GraphBuildRun.objects.bulk_update(
                run_batch,
                [
                    "build_key",
                    "build_generation",
                    "orchestration_version",
                    "build_kind",
                ],
                batch_size=batch_size,
            )
            run_batch.clear()
    if run_batch:
        GraphBuildRun.objects.bulk_update(
            run_batch,
            [
                "build_key",
                "build_generation",
                "orchestration_version",
                "build_kind",
            ],
            batch_size=batch_size,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("apps_knowledge_graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="graphartifact",
            name="kg_artifact_build_identity",
        ),
        migrations.RemoveConstraint(
            model_name="graphbuildrun",
            name="kg_build_stage_valid",
        ),
        migrations.AddField(
            model_name="graphartifact",
            name="build_key",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="graphartifact",
            name="build_generation",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="graphartifact",
            name="orchestration_version",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Legacy"), (1, "Scoped v1")],
                default=0,
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="build_key",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="build_generation",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="orchestration_version",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Legacy"), (1, "Scoped v1")],
                default=0,
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_owner",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="stage_marker",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="graphbuildrun",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("extracting", "Extracting"),
                    ("snapshotting", "Snapshotting"),
                    ("resolving", "Resolving"),
                    ("assembling", "Assembling"),
                    ("validating", "Validating"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("superseded", "Superseded"),
                    ("stale", "Stale"),
                    ("ontology", "Ontology"),
                    ("extraction", "Extraction"),
                    ("resolution", "Resolution"),
                    ("filtering", "Filtering"),
                    ("persistence", "Persistence"),
                    ("complete", "Complete"),
                ],
                default="ontology",
                max_length=16,
            ),
        ),
        migrations.RunPython(populate_build_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["build_kind", "scope_id", "build_key", "status"],
                name="kg_run_build_key_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="kg_run_status_lease_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_key__regex", "^[0-9a-f]{64}$")),
                name="kg_artifact_build_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(build_generation__gte=1),
                name="kg_artifact_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(orchestration_version__in=(0, 1)),
                name="kg_artifact_orchestration_version_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.UniqueConstraint(
                fields=(
                    "scope_type",
                    "scope_id",
                    "build_key",
                    "build_generation",
                ),
                name="kg_artifact_build_occurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(orchestration_version=1),
                fields=("scope_type", "scope_id", "build_generation"),
                name="kg_artifact_scope_generation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "queued",
                            "extracting",
                            "snapshotting",
                            "resolving",
                            "assembling",
                            "validating",
                            "active",
                            "failed",
                            "superseded",
                            "stale",
                            "ontology",
                            "extraction",
                            "resolution",
                            "filtering",
                            "persistence",
                            "complete",
                        ),
                    )
                ),
                name="kg_build_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_key__regex", "^[0-9a-f]{64}$")),
                name="kg_build_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(build_generation__gte=1),
                name="kg_build_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(orchestration_version__in=(0, 1)),
                name="kg_build_orchestration_version_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_kind", models.F("scope_type"))),
                name="kg_build_kind_matches_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(orchestration_version=0)
                    | models.Q(
                        orchestration_version=1,
                        build_kind="document",
                        stage__in=(
                            "queued",
                            "extracting",
                            "resolving",
                            "validating",
                            "active",
                            "failed",
                            "superseded",
                            "stale",
                        ),
                    )
                    | models.Q(
                        orchestration_version=1,
                        build_kind="collection",
                        stage__in=(
                            "queued",
                            "snapshotting",
                            "resolving",
                            "assembling",
                            "validating",
                            "active",
                            "failed",
                            "superseded",
                            "stale",
                        ),
                    )
                ),
                name="kg_build_stage_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(orchestration_version=0)
                    | models.Q(
                        orchestration_version=1,
                        stage="queued",
                        status="pending",
                    )
                    | models.Q(
                        orchestration_version=1,
                        stage__in=(
                            "extracting",
                            "snapshotting",
                            "resolving",
                            "assembling",
                            "validating",
                        ),
                        status="running",
                    )
                    | models.Q(
                        orchestration_version=1,
                        stage="active",
                        status="succeeded",
                    )
                    | models.Q(
                        orchestration_version=1,
                        stage="failed",
                        status="failed",
                    )
                    | models.Q(
                        orchestration_version=1,
                        stage__in=("superseded", "stale"),
                        status="cancelled",
                    )
                ),
                name="kg_build_stage_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_generation__gte", 0)),
                name="kg_build_lease_generation_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(orchestration_version=0)
                    | models.Q(lease_expires_at__isnull=True, lease_owner="")
                    | (
                        models.Q(orchestration_version=1)
                        & ~models.Q(lease_owner="")
                        & models.Q(lease_expires_at__isnull=False)
                        & models.Q(lease_generation__gte=1)
                    )
                ),
                name="kg_build_lease_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(orchestration_version=0)
                    | ~models.Q(stage__in=("active", "failed", "superseded", "stale"))
                    | models.Q(lease_expires_at__isnull=True, lease_owner="")
                ),
                name="kg_build_terminal_lease_clear",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(orchestration_version=1),
                fields=(
                    "build_kind",
                    "scope_type",
                    "scope_id",
                    "build_key",
                    "build_generation",
                ),
                name="kg_build_occurrence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(orchestration_version=1),
                fields=(
                    "build_kind",
                    "scope_type",
                    "scope_id",
                    "build_generation",
                ),
                name="kg_run_scope_generation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(orchestration_version=1),
                fields=("artifact",),
                name="kg_run_artifact_occurrence_unique",
            ),
        ),
    ]
