# Generated by Django 5.2.12 on 2026-08-18 16:26

import hashlib
import json

from django.db import migrations, models

_ARTIFACT_IDENTITY_FIELDS = (
    "scope_type",
    "scope_id",
    "source_hash",
    "ontology_version",
    "extractor_version",
    "resolver_version",
    "filter_policy_version",
    "embedding_model_signature",
    "ontology_checksum",
    "filter_policy_checksum",
    "resolution_config_checksum",
    "assembly_version",
    "assembly_config_checksum",
)


def _digest(payload):
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def populate_build_keys(apps, schema_editor):
    GraphArtifact = apps.get_model("apps_knowledge_graph", "GraphArtifact")
    GraphBuildRun = apps.get_model("apps_knowledge_graph", "GraphBuildRun")
    artifact_keys = {}
    for artifact in GraphArtifact.objects.order_by("pk").iterator():
        build_key = _digest(
            {
                "namespace": "legacy-graph-artifact-v1",
                "identity": {
                    field: str(getattr(artifact, field, ""))
                    for field in _ARTIFACT_IDENTITY_FIELDS
                },
            }
        )
        GraphArtifact.objects.filter(pk=artifact.pk).update(build_key=build_key)
        artifact_keys[artifact.pk] = build_key
    for run in GraphBuildRun.objects.order_by("pk").iterator():
        build_key = artifact_keys.get(run.artifact_id)
        if build_key is None:
            build_key = _digest(
                {
                    "namespace": "legacy-detached-graph-run-v1",
                    "run_id": run.pk,
                }
            )
        GraphBuildRun.objects.filter(pk=run.pk).update(
            build_key=build_key,
            build_kind=run.scope_type,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("apps_knowledge_graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="graphartifact",
            name="kg_artifact_build_identity",
        ),
        migrations.RemoveConstraint(
            model_name="graphbuildrun",
            name="kg_build_stage_valid",
        ),
        migrations.AddField(
            model_name="graphartifact",
            name="build_key",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="build_key",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="lease_owner",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="graphbuildrun",
            name="stage_marker",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="graphbuildrun",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("extracting", "Extracting"),
                    ("snapshotting", "Snapshotting"),
                    ("resolving", "Resolving"),
                    ("assembling", "Assembling"),
                    ("validating", "Validating"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("superseded", "Superseded"),
                    ("stale", "Stale"),
                    ("ontology", "Ontology"),
                    ("extraction", "Extraction"),
                    ("resolution", "Resolution"),
                    ("filtering", "Filtering"),
                    ("persistence", "Persistence"),
                    ("complete", "Complete"),
                ],
                default="ontology",
                max_length=16,
            ),
        ),
        migrations.RunPython(populate_build_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["build_kind", "scope_id", "build_key", "status"],
                name="kg_run_build_key_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphbuildrun",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="kg_run_status_lease_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_key__regex", "^[0-9a-f]{64}$")),
                name="kg_artifact_build_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphartifact",
            constraint=models.UniqueConstraint(
                fields=(
                    "scope_type",
                    "scope_id",
                    "build_key",
                    "source_hash",
                    "ontology_version",
                    "extractor_version",
                    "resolver_version",
                    "filter_policy_version",
                    "embedding_model_signature",
                    "ontology_checksum",
                    "filter_policy_checksum",
                    "resolution_config_checksum",
                    "assembly_version",
                    "assembly_config_checksum",
                ),
                name="kg_artifact_build_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "queued",
                            "extracting",
                            "snapshotting",
                            "resolving",
                            "assembling",
                            "validating",
                            "active",
                            "failed",
                            "superseded",
                            "stale",
                            "ontology",
                            "extraction",
                            "resolution",
                            "filtering",
                            "persistence",
                            "complete",
                        ),
                    )
                ),
                name="kg_build_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_key__regex", "^[0-9a-f]{64}$")),
                name="kg_build_key_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("build_kind", models.F("scope_type"))),
                name="kg_build_kind_matches_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "ontology",
                            "extraction",
                            "resolution",
                            "filtering",
                            "persistence",
                            "complete",
                        ),
                    ),
                    models.Q(
                        ("build_kind", "document"),
                        (
                            "stage__in",
                            (
                                "queued",
                                "extracting",
                                "resolving",
                                "validating",
                                "active",
                                "failed",
                                "superseded",
                                "stale",
                            ),
                        ),
                    ),
                    models.Q(
                        ("build_kind", "collection"),
                        (
                            "stage__in",
                            (
                                "queued",
                                "snapshotting",
                                "resolving",
                                "assembling",
                                "validating",
                                "active",
                                "failed",
                                "superseded",
                                "stale",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="kg_build_stage_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "ontology",
                            "extraction",
                            "resolution",
                            "filtering",
                            "persistence",
                            "complete",
                        ),
                    ),
                    models.Q(("stage", "queued"), ("status", "pending")),
                    models.Q(
                        (
                            "stage__in",
                            (
                                "extracting",
                                "snapshotting",
                                "resolving",
                                "assembling",
                                "validating",
                            ),
                        ),
                        ("status", "running"),
                    ),
                    models.Q(("stage", "active"), ("status", "succeeded")),
                    models.Q(("stage", "failed"), ("status", "failed")),
                    models.Q(
                        ("stage__in", ("superseded", "stale")),
                        ("status", "cancelled"),
                    ),
                    _connector="OR",
                ),
                name="kg_build_stage_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_generation__gte", 0)),
                name="kg_build_lease_generation_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lease_expires_at__isnull", True), ("lease_owner", "")),
                    models.Q(
                        models.Q(("lease_owner", ""), _negated=True),
                        ("lease_expires_at__isnull", False),
                        ("lease_generation__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="kg_build_lease_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "stage__in",
                            ("active", "failed", "superseded", "stale"),
                        ),
                        _negated=True,
                    ),
                    models.Q(
                        ("lease_expires_at__isnull", True),
                        ("lease_owner", ""),
                    ),
                    _connector="OR",
                ),
                name="kg_build_terminal_lease_clear",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphbuildrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        (
                            "queued",
                            "extracting",
                            "snapshotting",
                            "resolving",
                            "assembling",
                            "validating",
                            "active",
                            "failed",
                            "superseded",
                            "stale",
                        ),
                    )
                ),
                fields=("build_kind", "scope_type", "scope_id", "build_key"),
                name="kg_build_identity_unique",
            ),
        ),
    ]
