# Generated by Django 5.2.12 on 2026-03-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=2048)),
                ('activity_log', models.JSONField(default=list)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(choices=[('user', 'User'), ('exception', 'Exception')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aquillm_bugreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StackTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField()),
                ('traceback_text', models.TextField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=2048)),
                ('request_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stack_trace', to='apps_bug_reports.bugreport')),
            ],
            options={
                'db_table': 'aquillm_stacktrace',
            },
        ),
    ]
