# Generated by Django 6.0.3 on 2026-03-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_bug_reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StackTrace',
        ),
    ]
