// FilterKQLPreview.tsx
// read-only live display of the KQL query generated by the active filters
// sits directly under the FilterBar and above the QueryBuilder
// shows the exact query that is being sent to the feedbackql executor

import React from 'react';

interface FilterKQLPreviewProps {
  kql: string;
  loading: boolean;
}

const FilterKQLPreview: React.FC<FilterKQLPreviewProps> = ({ kql, loading }) => {
  return (
    <div
      className="mb-5 rounded-lg bg-scheme-shade_3 element-border overflow-hidden"
    >
      {/* header */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-scheme-contrast/20">
        <div className="flex items-center gap-2">
          <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-blue-600/20 text-blue-400">
            KQL
          </span>
          <span className="text-xs text-text-muted">
            {loading
              ? 'running query…'
              : 'generated from filters — updates as you change any control'}
          </span>
        </div>
        <span className="text-xs text-text-muted font-mono hidden sm:block">
          via feedbackql executor
        </span>
      </div>

      {/* query body */}
      <pre
        className="px-4 py-3 text-xs font-mono leading-relaxed overflow-x-auto whitespace-pre"
        style={{
          color: 'var(--color-accent-DEFAULT, #4a90d9)',
          background: 'var(--color-scheme-shade-4, #e8e8e8)',
          margin: 0,
          minHeight: '72px',
        }}
      >
        {kql || 'messages\n| order by feedback_submitted_at desc\n| limit 200'}
      </pre>

      {/* footer */}
      <div className="px-4 py-1.5 border-t border-scheme-contrast/10 bg-scheme-shade_3">
        <p className="text-xs text-text-muted">
          This query runs automatically when any filter changes. Use the{' '}
          <span className="font-mono text-text-normal">Visual query builder</span> below
          to append additional clauses, or type directly in the{' '}
          <span className="font-mono text-text-normal">query editor</span>.
        </p>
      </div>
    </div>
  );
};

export default FilterKQLPreview;